#if !defined(AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE)
#error "runtime_io_uring_socket_stream_tasks_fragment.hpp is a runtime_io_uring_socket_tasks implementation fragment"
#endif

#define AF_RUNTIME_IO_URING_SOCKET_STREAM_TASKS_FRAGMENT_INCLUDE 1
#include "runtime_io_uring_socket_stream_recv_tasks_fragment.hpp"
#include "runtime_io_uring_socket_stream_send_tasks_fragment.hpp"
#include "runtime_io_uring_socket_stream_vectored_tasks_fragment.hpp"
#undef AF_RUNTIME_IO_URING_SOCKET_STREAM_TASKS_FRAGMENT_INCLUDE
