#if !defined(AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE)
#error "runtime_io_uring_socket_tasks_fragment.hpp is a runtime_io_test_support implementation fragment"
#endif

#define AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE 1
#include "runtime_io_uring_socket_stream_tasks_fragment.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE

#define AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE 1
#include "runtime_io_uring_socket_datagram_tasks_fragment.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE

#define AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE 1
#include "runtime_io_uring_socket_accept_tasks_fragment.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE

#define AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE 1
#include "runtime_io_uring_socket_multishot_tasks_fragment.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE

#define AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE 1
#include "runtime_io_uring_socket_connect_tasks_fragment.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE

