#if !defined(AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE)
#error "runtime_io_file_rw_tasks_fragment.hpp is a runtime_io_file_tasks implementation fragment"
#endif

#define AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE 1
#include "runtime_io_file_basic_rw_tasks_fragment.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE

#define AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE 1
#include "runtime_io_file_vectored_rw_tasks_fragment.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE

#define AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE 1
#include "runtime_io_file_current_offset_tasks_fragment.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_FRAGMENT_INCLUDE
