#if !defined(AF_RUNTIME_IO_TEST_SUPPORT_DETAIL_INCLUDE)
#error "runtime_io_uring_socket_accept_tasks.hpp is a runtime_io_uring_socket_tasks implementation detail"
#endif

#define AF_RUNTIME_IO_TEST_SUPPORT_DETAIL_INCLUDE 1
#include "runtime_io_uring_socket_accept_basic_tasks.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_DETAIL_INCLUDE

#define AF_RUNTIME_IO_TEST_SUPPORT_DETAIL_INCLUDE 1
#include "runtime_io_uring_socket_accept_direct_tasks.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_DETAIL_INCLUDE

#define AF_RUNTIME_IO_TEST_SUPPORT_DETAIL_INCLUDE 1
#include "runtime_io_uring_socket_accept_multishot_tasks.hpp"
#undef AF_RUNTIME_IO_TEST_SUPPORT_DETAIL_INCLUDE
